services:
  porter-http:
    restart: on-failure
    image: porter:latest
    container_name: porter-http
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      # Default Porter port
      - "80:9155"
    volumes:
      - .:/code
      - ~/.local/share/nucypher:/nucypher
    command: ["nucypher-porter", "run",
              "--eth-endpoint", "${ETH_WEB3_PROVIDER_URI}",
              "--polygon-endpoint", "${POLY_WEB3_PROVIDER_URI}",
              "--domain", "${TACO_DOMAIN}"]
