# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - id: python_cache
      name: Retrieve Cached Python Dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('dev-requirements.txt', 'requirements.txt') }}

    - name: Upgrade pip
      if: steps.python_cache.outputs.cache-hit != 'true'
      run: python -m pip install --upgrade pip

    - name: Install dependencies (incl. updated code)
      run: pip install .[dev]

    - name: Run tests
      if: matrix.python-version != '3.9'
      run: |
        python -m pytest tests

    - name: Run tests (Coverage)
      if: matrix.python-version == '3.9'
      run: |
        coverage run --data-file=test_data -m pytest tests
        coverage xml -i --data-file=test_data -o coverage.xml

    - name: Upload test coverage to Codecov
      if: matrix.python-version == '3.9'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
        files: coverage.xml
